name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features

  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runs_on: ubuntu-latest
            archive: tar.gz
            exe_suffix: ""
            use_cross: false
          - target: aarch64-unknown-linux-gnu
            runs_on: ubuntu-latest
            archive: tar.gz
            exe_suffix: ""
            use_cross: false
          - target: x86_64-pc-windows-gnu
            runs_on: ubuntu-latest
            archive: zip
            exe_suffix: ".exe"
            use_cross: true
          - target: x86_64-apple-darwin
            runs_on: macos-latest
            archive: tar.gz
            exe_suffix: ""
            use_cross: false
          - target: aarch64-apple-darwin
            runs_on: macos-latest
            archive: tar.gz
            exe_suffix: ""
            use_cross: false
    runs-on: ${{ matrix.runs_on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross-compilation linker
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          mkdir -p .cargo
          cat >> .cargo/config.toml << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --release --target ${{ matrix.target }}
          
      - name: Package artifact
        run: |
          mkdir -p dist
          BIN="gdl"
          TARGET="${{ matrix.target }}"
          VERSION="${{ github.ref_name }}"
          if [ -z "$VERSION" ] || [ "$VERSION" = "main" ]; then
            VERSION="${{ github.sha }}"
          fi
          ARCHIVE_STEM="$BIN-$VERSION-$TARGET"
          cp "target/$TARGET/release/$BIN${{ matrix.exe_suffix }}" "dist/$BIN${{ matrix.exe_suffix }}"
          cd dist
          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip "$ARCHIVE_STEM.zip" "$BIN${{ matrix.exe_suffix }}"
          else
            tar czf "$ARCHIVE_STEM.tar.gz" "$BIN${{ matrix.exe_suffix }}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdl-${{ matrix.target }}
          path: dist/*

  release:
    if: always() && startsWith(github.ref, 'refs/tags/') && !cancelled()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
        continue-on-error: true

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
